CREATE TABLE CHOICE(
	C_TYPE VARCHAR2(50) PRIMARY KEY,
	C_SHORT NUMBER(5),
	C_TALL NUMBER(5),
	C_GRANDE NUMBER(5)
);

INSERT INTO CHOICE(C_TYPE, C_SHORT, C_TALL, C_GRANDE)
VALUES('오늘의 커피', 2500, 3000, 3500)

-- 커피 메뉴판
SELECT *
FROM CHOICE;